### ISSUE TITLE
[BUG] "Key.split is not a function or its return value is not iterable"

### ISSUE THREAD

**Issue by ctbritt** [p4535992/conditional-visibility#44]
**Module Version:** v0.6.7

**Describe the bug**
when attempting to roll items with an itemMacro attached to it, the following error occurs: 

```
ncaught (in promise) TypeError: key.split is not a function or its return value is not iterable
[Detected 3 packages: conditional-visibility, midi-qol, more-hooks-5e]
    at Module.getProperty (helpers.mjs:294:22)
    at Localization.localize (foundry.js:4602:27)
    at i18n (lib.js:152:22)
    at api.js:954:47
    at Array.find (<anonymous>)
    at Object.canSee (api.js:953:36)
    at Workflow.checkAttackAdvantage (workflow.js:842:65)
    at async Item5e.doItemRoll (itemhandling.js:730:2)
    at async Item5e.rollPatch (roll.js:8:23)
```

**To Reproduce**
1. Have CV activated
2. Click an item on a char sheet with a ItemMacro attached to it. 
3. Watch error message populate the Console.
4. 
**Expected behavior**
The item should function as expected given the ItemMacro

**Browser:**
Chrome 102.0.5005.61 

**Foundry Version:** 
v9.269

**Game System:** 
Dnd5e 1.6.1

**Additional context**
all items function normally if deactivating CV

**Comment by p4535992** [comment]
Fixed with 0.6.8
